#pragma once
enum MULTI_OBJECT_TYPE {
	// PLAYER
	MULTI_PLAYER,

	// MOVE
	MULTI_MOVE_FIRE,
	MULTI_MOVE_WATER,
	MULTI_MOVE_THUNDER,
	MULTI_MOVE_WIND,

	// ATTACK
	MULTI_ATTACK_FIRE,
	MULTI_ATTACK_WATER,
	MULTI_ATTACK_THUNDER,
	MULTI_ATTACK_THUNDER2,
	MULTI_ATTACK_WIND,

	// ENEMY
	MULTI_ENEMY1,
	MULTI_ENEMY2,
	MULTI_ENEMY3,
	MULTI_ATTACK_ENEMY2,

	// SKILLPOINT
	MULTI_SKILL_POINT_SMALL,
	MULTI_SKILL_POINT_MIDIUM,
	MULTI_SKILL_POINT_BIG,
};
