/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113034-g89215237dd-20231220"
#endif /* AVUTIL_FFVERSION_H */
